# Xcode
trigger:
- mobile-dev

pool:
  vmImage: 'macos-latest'

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: apple-distribution.p12

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles' # Options: secureFiles, sourceRepository
    provProfileSecureFile: 'azuredevops.mobileprovision'
    removeProfile: true # Optional

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo $(FASTLANE_PASS)
      npm install
      FASTLANE_PASSWORD=$(FASTLANE_PASS) && npm run-script deploy:ios:localizalia:beta
      FASTLANE_PASSWORD=$(FASTLANE_PASS) && npm run-script deploy:ios:nogartel:beta

