# Xcode
trigger:
- mobile-dev

pool:
  vmImage: 'macos-latest'

variables:
  - name: FASTLANE_PASSWORD
    value: $(FASTLANE_PASS)
  - name: FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD
    value: $(FASTLANE_APP_SPECIFIC)

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: ios-dev.p12

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles' # Options: secureFiles, sourceRepository
    provProfileSecureFile: 'azuredevops.mobileprovision'
    removeProfile: true # Optional

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles' # Options: secureFiles, sourceRepository
    provProfileSecureFile: 'comfleetmapnogartel_AppStore_1650450346.mobileprovision'
    removeProfile: true # Optional

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles' # Options: secureFiles, sourceRepository
    provProfileSecureFile: 'manager.mobileprovision'
    removeProfile: true # Optional

- task: DownloadSecureFile@1
  name: provProfileManager
  displayName: 'Download profile manager'
  inputs:
    secureFile: 'manager.mobileprovision'

- task: DownloadSecureFile@1
  name: provProfileNogartel
  displayName: 'Download profile nogartel'
  inputs:
    secureFile: 'comfleetmapnogartel_AppStore_1650450346.mobileprovision'

- task: DownloadSecureFile@1
  name: provProfileWuizy
  displayName: 'Download profile wuizy'
  inputs:
    secureFile: 'comfleetmapwuizy.mobileprovision'

- task: DownloadSecureFile@1
  name: provProfile
  displayName: 'Download profile'
  inputs:
    secureFile: 'azuredevops.mobileprovision'

- task: DownloadSecureFile@1
  name: apiKey
  displayName: 'Download api key'
  inputs:
    secureFile: 'AuthKey_BKMNZXA9H4.p8'

- task: Bash@3
  displayName: 'Install'
  inputs:
    name: 'Install'
    targetType: 'inline'
    script: |
      echo fs $(FASTLANE_SESSION)
      echo using profile $(provProfile.secureFilePath)
      npm install

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo using profile $(provProfile.secureFilePath)
      export FASTLANE_PASSWORD=$(FASTLANE_PASS)
      export FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=$(FASTLANE_APP_SPECIFIC)
      export APP_STORE_CONNECT_API_KEY_KEY_FILEPATH=$(apiKey.secureFilePath)

      export FL_PROJECT_PROVISIONING_PROFILE_FILE=$(provProfile.secureFilePath)
      npm run-script build:ios:localizalia
      mobile/deploy-ios.sh

      export FL_PROJECT_PROVISIONING_PROFILE_FILE=$(provProfileNogartel.secureFilePath)
      npm run-script build:ios:nogartel
      mobile/deploy-ios.sh

      export FL_PROJECT_PROVISIONING_PROFILE_FILE=$(provProfileManager.secureFilePath)
      npm run-script build:ios:manager
      mobile/deploy-ios.sh

      export FL_PROJECT_PROVISIONING_PROFILE_FILE=$(provProfileWuizy.secureFilePath)
      npm run-script build:ios:wuizy
      mobile/deploy-ios.sh

