# Xcode
trigger:
- mobile-dev

pool:
  vmImage: 'macos-latest'

variables:
  - name: FASTLANE_PASSWORD
    value: $(FASTLANE_PASS)
  - name: FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD
    value: $(FASTLANE_APP_SPECIFIC)

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: apple-distribution.p12

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles' # Options: secureFiles, sourceRepository
    provProfileSecureFile: 'azuredevops.mobileprovision'
    removeProfile: true # Optional

- task: DownloadSecureFile@1
  name: provProfile
  displayName: 'Download profile'
  inputs:
    secureFile: 'azuredevops.mobileprovision'

task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      npm install

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      FL_PROJECT_PROVISIONING_PROFILE_FILE=$(provProfile.secureFilePath)
      npm run-script deploy:ios:localizalia:beta
      cd ios/App
      gem install xcodeproj
      ruby addGooglePlist.rb
      echo "add_plugin versioning"
      fastlane add_plugin versioning
      fastlane install_plugins
      fastlane beta

