# Xcode
trigger:
- mobile-dev

pool:
  vmImage: 'macos-latest'

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: apple-distribution.p12
    #certPwd: # Optional
    #keychain: 'temp' # Options: default, temp, custom
    #keychainPassword: # Required when keychain == Custom || Keychain == Default
    #customKeychainPath: # Required when keychain == Custom
    #deleteCert: # Optional
    #deleteCustomKeychain: # Optional
    #signingIdentity: # Optional
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles' # Options: secureFiles, sourceRepository
    provProfileSecureFile: # Required when provisioningProfileLocation == SecureFiles
    provProfileSourceRepository: azuredevops.mobileprovision
    removeProfile: true # Optional

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      npm install
      npm run-script deploy:ios:localizalia:beta
      
