version: 0.2

phases:
  install:
    commands:
      - echo Install started on `date`
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
      - tar -xvf android-sdk_r24.4.1-linux.tgz
      - sudo mv android-sdk-linux /opt/
      - export ANDROID_HOME=/opt/android-sdk-linux
      - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
  build:
    commands:
      - aws s3api get-object --bucket secrets-fleetmap --key google-secret.json mobile/google-secret.json
      - npm install
      - npm run-script deploy:android:localizalia
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
    - './android/app/build/outputs/**/*.apk'
  discard-paths: yes
