version: 0.2

phases:
  install:
    commands:
      - echo Install started on `date`
      - aws s3api get-object --bucket secrets-fleetmap --key google-secret.json mobile/google-secret.json
      - aws s3api get-object --bucket keystore --key google-secret.json mobile/keystore
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
      - tar -xvf android-sdk_r24.4.1-linux.tgz
      - sudo mv android-sdk-linux /opt/
      - export ANDROID_HOME=/opt/android-sdk-linux
      - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
      - mkdir $ANDROID_HOME/licenses
      - echo 24333f8a63b6825ea9c5514f83c2829b004d1fee > $ANDROID_HOME/licenses/android-sdk-license
      - /opt/android-sdk-linux/tools/android update sdk --no-ui
  build:
    commands:
      - npm install
      - npm run-script deploy:android:localizalia
artifacts:
  files:
    - './android/app/build/outputs/**/*.apk'
  discard-paths: yes
