version: 0.2

phases:
  build:
    commands:
      - npm install
      - gem install bundler
      - npm run-script deploy:android:localizalia
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
    - './android/app/build/outputs/**/*.apk'
  discard-paths: yes
