const getters = {
  user: state => state.user.user,
  avatar: state => state.user.user.attributes.avatar,
  name: state => state.user.user.name,
  map: state => state.map,
  devices: state => state.user.devices,
  loading: state => state.app.loading,
  historyMode: state => state.transient.historyMode,
  minPos: state => state.map.minPos,
  maxPos: state => state.map.maxPos,
  isPlaying: state => state.transient.isPlaying,
  alerts: state => state.user.alerts,
  events: state => state.transient.events,
  dataLoaded: state => state.transient.dataLoaded,
  groups: state => state.user.groups,
  drivers: state => state.user.drivers,
  geofences: state => state.user.geofences,
  unreadItems: state => state.unreadItems,
  showLabels: state => state.settings.showLabels,
  currentTime: state => state.currentTime,
  trips: state => state.transient.trips,
  showGeofences: state => state.map.showGeofences,
  showLineGeofences: state => state.map.showLineGeofences,
  showPOIs: state => state.map.showPOIs,
  show3dBuildings: state => state.map.show3dBuildings,
  tableCollapsed: state => state.map.tableCollapsed,
  vehicles3dEnabled: state => state.settings.vehicles3d,
  portrait: state => state.transient.portrait
}

export default getters
