default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :build do
    gradle(task: "build")
  end

  lane :beta do
    android_get_version_name(
        gradle_file: "app/build.gradle" # optional
      )

      android_set_version_name(
        version_name: ENV["VERSION_NAME"],
        gradle_file: "app/build.gradle" # optional
      )

      android_get_version_code(
        gradle_file: "app/build.gradle" # optional
      )

      android_set_version_code(
        version_code: ENV["VERSION_CODE"],
        gradle_file: "app/build.gradle" # optional
      )
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    upload_to_play_store(track: 'beta')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
        task: 'bundle',
        build_type: 'Release',
        properties: {
            "android.injected.signing.store.file" => "/Users/Shared/keystore",
            "android.injected.signing.store.password" => "password",
            "android.injected.signing.key.alias" => "key0",
            "android.injected.signing.key.password" => "password",
          }
      )
    upload_to_play_store(skip_upload_apk: true)
  end
end
