// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b6d2631a-1b45-4894-9ec8-0b26ca3020ae",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_7XX6xixph",
    "aws_user_pools_web_client_id": "38la9o74tmq4lu718tmriccblf",
    "oauth": {
        "domain": "auth-prod.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://pinme.io/",
        "redirectSignOut": "https://pinme.io/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_mobile_analytics_app_id": "0209da656f784a2fad69793a32251916",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
