// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:382a2127-91bf-4ba6-92c0-396fde025ead",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4IQkoDGPc",
    "aws_user_pools_web_client_id": "2sehb31hlq83s6lu5pqu1so5uc",
    "oauth": {},
    "aws_mobile_analytics_app_id": "0209da656f784a2fad69793a32251916",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://yh5deqyr7ndt7mjzpxx5jpful4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-sizoepqr2rc3pev6sufpxxrhqa"
};


export default awsmobile;
