name: Deploy to Google Play Store

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically 
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'     
      - name: Build and sign APK
        run: |
          npm install --legacy-peer-deps
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > mobile/keystore
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_PLAY_STORE }}" > mobile/google-secret.json
          npm run-script deploy:android:manager
