name: Deploy to Google Play Store

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build and sign APK
        run: |
          npm install 
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > mobile/keystore
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_PLAY_STORE }}" > mobile/google-secret.json
          npm run-script deploy:android:manager
