name: Localizalia to App Store

on:
  push:
    branches:
      - localizalia

env:
  COGNITO_CLIENT_ID: 2ml2d0h1qk7q614qc3bclg2alj
  USER_POOL_ID: eu-west-3_3zjuFkIv8
  AUTH_DOMAIN: fleetmap.auth.eu-west-3.amazoncognito.com
  ENVIRONMENT: ios
  APP_STORE_CONNECT_API_KEY_KEY: "${{vars.APP_STORE_CONNECT_API_KEY_KEY}}"
  APP_STORE_CONNECT_API_KEY_ISSUER_ID: "${{vars.APP_STORE_CONNECT_API_KEY_ISSUER_ID}}"
  APP_STORE_CONNECT_API_KEY_KEY_ID: "${{vars.APP_STORE_CONNECT_API_KEY_KEY_ID}}"
  PROFILE_NAME: match AppStore com.fleetmap.localizalia
  SERVER_HOST: localizalia.net
  SOCIAL_SIGN_IN: false
  MAPBOX_TOKEN: pk.eyJ1IjoiZmxlZXRtYXAtbG9jYWxpemFsaWEiLCJhIjoiY2x1N2Jlc2IyMDNibTJxbjA0M3o4dGI3ZCJ9.-HkvoIwi14RY7IwvBeNWoQ
  APP_NAME: Localizalia
  PACKAGE_NAME: com.fleetmap.localizalia
  SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
  WEB_SOCKET_HOST: traccar-eu.fleetmap.pt

  # sentry account: ios.localizalia@fleetmap.io
  SENTRY_DSN: https://04373d5844104d2c4e217cfbd028ce41@o4507418817855488.ingest.de.sentry.io/4507418823032912


jobs:
  deploy:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Select latest Xcode
        run: |
          LATEST=$(ls /Applications | grep Xcode | sort -Vr | head -n 1)
          sudo xcode-select -switch "/Applications/$LATEST"
          xcodebuild -version
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: install with fontawesome
        run: |
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/
          npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
          npm install --legacy-peer-deps

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: build
        run: |
          echo '${{ secrets.GOOGLE_CLOUD_AUTH }}' > gc_keys.json
          npm run-script build:ios
      - name: deploy
        run: mobile/deploy-ios.sh
