name: Deploy to App Store

on:
  push:
    branches:
      - main

env:
  COGNITO_CLIENT_ID: 2ml2d0h1qk7q614qc3bclg2alj
  USER_POOL_ID: eu-west-3_3zjuFkIv8
  AUTH_DOMAIN: fleetmap.auth.eu-west-3.amazoncognito.com
  SERVER_HOST: api.pinme.io
  APP_NAME: Manager
  PACKAGE_NAME: com.fleetmap.manager
  MAPBOX_TOKEN: pk.eyJ1IjoibWFwYm94LWlvcy1tYW5hZ2VyIiwiYSI6ImNsc3hxcnJhbDA1MngyaW9ldzl3N3E1NnIifQ.DMs8qVULqGGb6JGILvjFcg
  ENVIRONMENT: ios
  APP_STORE_CONNECT_API_KEY_KEY: "${{vars.APP_STORE_CONNECT_API_KEY_KEY}}"
  APP_STORE_CONNECT_API_KEY_ISSUER_ID: "${{vars.APP_STORE_CONNECT_API_KEY_ISSUER_ID}}"
  APP_STORE_CONNECT_API_KEY_KEY_ID: "${{vars.APP_STORE_CONNECT_API_KEY_KEY_ID}}"

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
      - name: install with fontawesome
        run: |
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/
          npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
          npm install --legacy-peer-deps

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: build
        run: npm run-script build:ios
      - name: install fastlane
        run: |
          echo '${{ secrets.GOOGLE_CLOUD_AUTH }}' > gc_keys.json
          mobile/build-ios.sh
      #- name: deploy manager
      #  run: mobile/deploy-ios.sh
      #  env:
      #    PROFILE_NAME: match AppStore com.fleetmap.manager

      - name: deploy nogartel
        run: mobile/deploy-ios.sh
        env:
          SERVER_HOST: nogartel.fleetmap.io
          SOCIAL_SIGN_IN: true
          MAPBOX_TOKEN: pk.eyJ1Ijoibm9nYXJ0ZWwiLCJhIjoiY2x1N2I1NzlpMDRnbTJrbXAzeGNoaDFlbCJ9.MJCdAPkK8l2Kv81Rs2tORw
          APP_NAME: Nogartel
          PACKAGE_NAME: com.fleetmap.nogartel
          PROFILE_NAME: match AppStore com.fleetmap.nogartel

      - name: deploy localizalia
        run: mobile/deploy-ios.sh
        env:
          SERVER_HOST: localizalia.net
          SOCIAL_SIGN_IN: false
          MAPBOX_TOKEN: pk.eyJ1IjoiZmxlZXRtYXAtbG9jYWxpemFsaWEiLCJhIjoiY2x1N2Jlc2IyMDNibTJxbjA0M3o4dGI3ZCJ9.-HkvoIwi14RY7IwvBeNWoQ
          APP_NAME: Localizalia
          PACKAGE_NAME: com.fleetmap.localizalia







